apiVersion: v1
kind: Service
metadata:
  name: frontend-warabej793-stg-v3
  namespace: front-end-v3
  labels:
    environment: stg
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" # Create an internal Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"      # Use a Network Load Balancer for high performance
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60" # Optional: Idle timeout in seconds
spec:
  type: LoadBalancer
  selector:
    app: frontend-warabej793-stg-v3
  ports:
    - protocol: TCP
      port: 80         # The port exposed by the Load Balancer
      targetPort: 3000 # The port your application is listening on
